### ISSUE TITLE
Support dumping DICOM files with no extension

### ISSUE THREAD

**Issue by mattwarkentin** [smikitky/vscode-dicom-dump#18]
Hi @smikitky,

Great extension! I was wondering if there would be some way to allow dumping of DICOM files with no file extension. It is my understanding that the DICOM Standard does not require a file extension to be compliant to the standard. I often find myself interacting with DICOM files without an extension and I am not able to "right click" and dump the file contents as per usual.

Thanks for your consideration.

**Comment by smikitky** [comment]
Please use the `alwaysShowMenu` option here: https://github.com/smikitky/vscode-dicom-dump?tab=readme-ov-file#configuration

Fell free to reopen this if it doesn't work.

**Comment by mattwarkentin** [comment]
This is great, thanks!
