### ISSUE TITLE
Just Installed and It Locks Up VS Code

### ISSUE THREAD

**Issue by PCJimmmy** [smikitky/vscode-dicom-dump#3]
Doing Kaggle.com on RNSA and wanted to view dicom data in visual basic.  

Found your code while searching for a vb.net viewer/decoder.  

Added and installed in VS code - latest version.  Anytime I come near you code it locks up system - eventually message to reopen window.  Have not tried installing in Visual Studio.

Should it work in VS Code ?  It certainly seems to install there ok.

The image data can be displayed in the Java link you supplied - so they are good.

**Comment by smikitky** [comment]
This extension works only on Visual Studio _Code_ (VS Code), not on Visual Studio nor VB.net.

By "anytime I come near you code", you mean VS Code hangs up when you click "DICOM: Dump DICOM Tags", right? Then could you share the actual DICOM file that is causing the trouble?

**Comment by PCJimmmy** [comment]
Now believe the issue in VS Code rather than your extension.  I think I have successfully uninstalled it from VS Code but vs code was still hanging up.  It took a while to close that folder successfully and VS code now operating normally.

Have a deep learning script running in VS Code now that should be done in few hours, so I can validate cause.  Don’t want to test my idea and kill the script that’s been running overnight. 

I opened a folder that had 25000 (the full dicom download from RSNA challenge on Kaggle) dicom files  – it seems like VS code might be attempting to create thumbnails or some similar chore.  I am wondering if the same hang-up occurs when I open a folder, with VS Code that contains 25000 jpg or png’s – that’s the nature of what I will be trying as soon as my Python script ends.  Will also test opening a folder with only one dicom file, etc.

Did you observe any such delays when you opened a folder in VS code containing a large number of dicom files?

Will update your GitHub later today.

That’s for the quick response.  

Jim

Sent from Mail for Windows 10

**Comment by smikitky** [comment]
I doubt the thumbnails were created by VS Code (it knows nothing about DICOM).

Anyway, VS Code is basically a code editor, and it's not good at handling thousands of files in a single directory. When I have to handle dozens of thousands of similar files, I usually do [something like this](https://medium.com/eonian-technologies/file-name-hashing-creating-a-hashed-directory-structure-eabb03aa4091).

**Comment by PCJimmmy** [comment]
Did not say it created thumbnails – what I think is that it’s trying to create some.

Open a folder with a single dicom.   Use your code to dump – things work great.

Open a folder with 3201 dicom files – seems like a touch of hesitation but can still open and dump a dicom file.

Open a folder with 28,000 files – hangs up.  

Eventually this dialog message.


Select Keep Waiting – another minute or two and than  I can dump a tag (I had selected Reopen before).

So VS is trying to make some sense of the dicom files.  Ie, its TRYING to make a thumbnail but since it knows nothing about dicom it just hangs for a few minutes.

Open folder in VS with 18000 png files – within a few seconds a thumbnail is created of the first file and can be viewed but it still hangs for a long time – I assume its creating thumbnails for all 18000 images.

This behavior with or without your extension installed.

So its not you – will you close the issue or should I do it.

Thanks

Jim


Sent from Mail for Windows 10

**Comment by smikitky** [comment]
VS Code is not an image viewer in the first place, and I don't think VS Code creates thumbnails of any type. Of course it does not even know DICOM is an image format.

Before you actually click "DICOM: Dump DICOM Tags" menu, the script of this extension is not even loaded. All it does is to [add two menu items](https://github.com/smikitky/vscode-dicom-dump/blob/master/package.json#L89-L112) via [contribution points](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus). If it's already slow before you click the menu item, maybe VS Code is doing things like file type matching or icon matching. It's basically a performance issue on the VS Code's side, and I can do nothing about that.

Anyway, I would say having more than a few thousand files in a single directory is usually a bad idea, and it can cause many applications to freeze. Even Windows Explorer has performance issues with a directory with more than 10,000 files. You should try to reduce the number of files by creating subdirectories.

**Comment by PCJimmmy** [comment]
For sure not an image viewer, but you can view images when you open a folder in VS explorer.    I think the performance issues you reference for Windows explorer are being magnified in VS for file types that it does not recognize.

The dump extension working fine – nice job – thanks

The Kaggle.com format is pretty much always all the “images” in single folder.  Since I am only at month 3 of knowing Python I would likly make a mess of trying to read the images if I spread them across too many directories.  As it is I often spend an hour on a single line of simple code.

Thanks again for the prompt responses - will be using your extension for at least the next month as as work on the RSNA Kaggle.com challenge.
